name: esc_pos_bluetooth
description: The library allows to print receipts using an ESC/POS thermal Bluetooth printer.
version: 0.4.1
homepage: https://github.com/andrey-ushakov/esc_pos_bluetooth

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0
  
  esc_pos_utils_plus: ^2.0.4 
  # esc_pos_utils: ^1.1.0
  # esc_pos_utils:
  # path: ../esc_pos_utils
  #flutter_bluetooth_basic: ^0.1.7 
  # flutter_bluetooth_basic:
  #   git:
  #     url: https://github.com/nsy738/flutter_bluetooth_basic
  #     ref: master
  flutter_bluetooth_classic_serial: ^1.0.3 
  #flutter_bluetooth_serial: ^0.4.0
  flutter_blue_plus: ^1.35.5
  image: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
